In [1]:
import fynance as fy
import numpy as np

In [2]:
X = np.random.rand(50000 * 2)

In [3]:
%timeit fy.roll_mdd(X)

633 µs ± 46.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
%timeit fy.roll_mdd(X, w=500)

351 ms ± 32.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
%timeit fy.roll_mdd(X)

5.04 s ± 398 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
%timeit fy.roll_mdd(X, w=500)

105 ms ± 3.11 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
%timeit fy.roll_drawdown(X, w=500)

52.9 ms ± 3.03 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
%timeit fy.roll_annual_volatility(X, period=252)

4.65 ms ± 317 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [3]:
%timeit fy.roll_annual_volatility(X, period=252)

12.4 s ± 181 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
%timeit fy.roll_annual_volatility(X, period=252, c=True)

12.7 s ± 266 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
%timeit fy.roll_annual_return(X, period=252)

9.84 ms ± 306 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
%timeit fy.roll_annual_return(X, period=252, c=True)

7.31 ms ± 511 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [7]:
%timeit fy.calmar(X)

14.3 ms ± 290 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
%timeit fy.calmar(X, new=True)

688 µs ± 5.24 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [3]:
%timeit fy.drawdown(X)

279 µs ± 9.61 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [3]:
%timeit fy.drawdown(X, c=True)

253 µs ± 9.27 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
%timeit fy.drawdown(X)

981 µs ± 16.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
X = np.random.rand(50000 * 2)

In [5]:
%timeit fy.drawdown(X)

496 µs ± 22.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [3]:
%timeit fy.drawdown(X, c=True)

488 µs ± 15.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
%timeit fy.drawdown(X)

576 µs ± 40.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
fy.drawdown(X)

array([0.        , 0.        , 0.56985538, ..., 0.20032256, 0.58900233,
       0.36896543])

In [5]:
X

array([0.11866583, 0.78236759, 0.33653121, ..., 0.79966264, 0.41099007,
       0.63102289])

In [3]:
%timeit fy.emstd(X, 30)

1.03 ms ± 37.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [3]:
%timeit fy.emstd(X, 30)

/home/arthur/GitHub/Fynance/fynance/tools/momentums.py:369: RuntimeWarning: overflow encountered in double_scalars
  return emstd_cy(X.flatten().astype(np.float64), alpha=float(alpha))
/home/arthur/GitHub/Fynance/fynance/tools/momentums.py:369: RuntimeWarning: invalid value encountered in sqrt
  return emstd_cy(X.flatten().astype(np.float64), alpha=float(alpha))


115 ms ± 2.95 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
%timeit fy.emstd(X, 30, c=True)

2.52 ms ± 73.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [3]:
%timeit fy.wmstd(X, 30)

1.83 s ± 15.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
%timeit fy.wmstd(X, 30, c=True)

6.17 ms ± 279 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [3]:
%timeit fy.smstd(X, 30)

826 ms ± 68.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
%timeit fy.smstd(X, 30, c=True)

1.43 ms ± 17.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
%timeit fy.smstd(X, 30, c=True)

4.26 ms ± 160 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [2]:
X = np.random.rand(50000, 2)

In [3]:
%timeit fy.ema(X, 30)

496 µs ± 11.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
X = np.random.rand(50000 * 2)

In [7]:
%timeit fy.ema(X, 30)

496 µs ± 19.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [14]:
%timeit fy.ema(X, 30)

547 µs ± 22.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [2]:
X = np.random.rand(50000, 2)

In [3]:
%timeit fy.wma(X, 30)

4.64 ms ± 282 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
X = np.random.rand(50000 * 2)

In [5]:
%timeit fy.wma(X, 30)

3.41 ms ± 245 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
%timeit fy.wma(X, 30)

727 ms ± 30.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
%timeit fy.sma(X, 30)

818 µs ± 73.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
%timeit fy.sma(X, 30, c=True)

501 µs ± 18.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
%timeit fy.sma(X, 30)

955 µs ± 90 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
%timeit fy.sma(X, 30, c=True)

534 µs ± 37.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [17]:
%timeit fy.sma(X, 30)

27.3 µs ± 2.62 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [18]:
%timeit fy.sma(X, 30, c=True)

15.5 µs ± 232 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [22]:
X = np.array([60, 100, 80, 120, 160, 80])

x_1d = X
x_2d = X.reshape([6, 1]).astype(np.float64)
ma_1d = fy.wma(x_1d, 4, dtype=np.float32)
ma_2d = fy.wma(x_2d, 4, dtype=np.float32)

assert ma_1d.dtype == np.float32
assert (ma_1d == ma_2d.flatten()).all()
assert ma_1d.shape == (6,)
assert ma_2d.shape == (6, 1)
assert (fy.wma(x_1d, 7) == fy.wma(x_1d, 6)).all()
assert (fy.wma(x_2d, 2, axis=1) == x_2d).all()

/home/arthur/GitHub/Fynance/fynance/tools/_wrappers.py:78: UserWarning: 7 lags is out of bounds for axis 0 with size 6
  k, axis, X.shape[axis]
/home/arthur/GitHub/Fynance/fynance/tools/_wrappers.py:78: UserWarning: 2 lags is out of bounds for axis 1 with size 1
  k, axis, X.shape[axis]


AssertionError: 

In [12]:
fy.wma(x_2d.T, 1, axis=0)

array([[80, 80, 80, 80, 80, 80]])

In [26]:
X2 = np.array([[60, 60], [100, 100], [80, 80], [120, 120], [160, 160], [80, 80]])
fy.wma(X2, , axis=1)

array([[80, 80],
       [80, 80],
       [80, 80],
       [80, 80],
       [80, 80],
       [80, 80]])

In [31]:
fy.wma(np.concatenate((X2.T, X2.T)), 3, axis=0)

array([[80, 80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80, 80]])

$$ t^+ $$

___

In [6]:
int(True)

1

In [7]:
int(False)

0