In [1]:
import numpy as np

In [86]:
def wrapper(func):
    def check_array(x, *args, dtype=None, shape=None, **kwargs):
        if dtype is None:
            dtype = x.dtype

        if shape is None:
            shape = x.shape
        
        if x.dtype != np.float64:
            x = x.astype(np.float64)
        
        if dtype != np.float64:
            return func(x, *args, dtype=dtype, shape=shape, **kwargs).astype(dtype)

        return func(x, *args, dtype=dtype, shape=shape, **kwargs)
    return check_array

In [91]:
@wrapper
def test(x, axis=0, dtype=None, shape=None):
    if axis < 0 or axis > len(shape):
        raise ValueError('Unvailable axis argument.')

    index = [slice(None) for i in range(axis)]

    for i in range(x.size):
        x[index + [i]] = i + 2
        
    return x

In [88]:
a = np.arange(27)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [62]:
%timeit test(a)

126 ms ± 2.52 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [63]:
%timeit test(a, dtype=np.int64, shape=(27,))

132 ms ± 4.62 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [93]:
test(a)

float64


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [53]:
a.astype(np.float64)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
       28.])

In [67]:
a.dtype == np.int64

True

In [65]:
import fynance as fy

fy.sma(a, lags=64)

/home/arthur/GitHub/Fynance/fynance/tools/momentums.py:34: UserWarning: Lags parameters is greater than size of series.
  warnings.warn('Lags parameters is greater than size of series.')


array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. ])

In [83]:
isinstance(a.dtype, np.dtype('int'))

TypeError: isinstance() arg 2 must be a type or tuple of types

In [72]:
type(a.dtype)

numpy.dtype

In [73]:
type(np.int64)

type

NameError: name 'xrange' is not defined

In [78]:
np.dtype('float')

dtype('float64')

In [80]:
a.astype(np.float64).dtype

dtype('float64')

In [96]:
np.cumsum(a, out=a)

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300, 325,
       351])

In [97]:
a

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300, 325,
       351])

In [98]:
a.shape

(27,)

In [99]:
np.zeros(a.shape)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [101]:
a = np.arange(27)

In [111]:
series = np.array([[60, 60], [100, 100], [80, 80], [120, 120], [160, 160], [80, 80]])

In [112]:
series.astype(np.float64)

array([[ 60.,  60.],
       [100., 100.],
       [ 80.,  80.],
       [120., 120.],
       [160., 160.],
       [ 80.,  80.]])

In [113]:
series

array([[ 60,  60],
       [100, 100],
       [ 80,  80],
       [120, 120],
       [160, 160],
       [ 80,  80]])

In [118]:
np.sum(series, axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [117]:
raise np.AxisError(3, 2)

AxisError: axis 3 is out of bounds for array of dimension 2

In [119]:
np.astype()

AttributeError: module 'numpy' has no attribute 'astype'

In [123]:
np.asarray(a, dtype=np.float64)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26.])

In [124]:
np.array()

TypeError: array() missing required argument 'object' (pos 1)

In [131]:
np.dtype('d')

dtype('float64')

In [134]:
series = np.array([60, 100, 80, 120, 160, 80])
fy.wma(series, lags=3)

array([ 60.        ,  86.66666667,  83.33333333, 103.33333333,
       133.33333333, 113.33333333])

In [137]:
series = np.array([120, 160, 80, 120, 160, 80])
fy.wma(series, lags=3)

array([120.        , 146.66666667, 113.33333333, 113.33333333,
       133.33333333, 113.33333333])